## 1. `tf.pad()`     
用来对tensor的大小进行扩展，包括水平、垂直、深度(通道)等
```python
tf.pad(tensor, paddings, mode='CONSTANT', name=None, constant_values=0)   
```  
- paddings:设置填充的大小
- mode:填充方式，默认是CONSTANT,还有REFLECT和SYMMETRIC
- constant_values：CONSTANT填充方式的填充值

In [2]:
import tensorflow as tf
import numpy as np

In [5]:
# case
a = np.array(np.arange(1, 10)).reshape(3, 3)

sess = tf.InteractiveSession()
b = tf.pad(a, [[1, 1], [2, 2]])
print(sess.run(b))

[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 7 8 9 0 0]
 [0 0 0 0 0 0 0]]


- [1,1]表示的是垂直方向上的填充，第一个1表示的是向上的填充行数，第二个1表示的是向下的填充行数   
- [2,2]表示的水平方向上的填充，第一个2表示的向左的填充行数，第二个2表示的是向右的填充行数

In [4]:
import tensorflow as tf
from tensorflow import keras  
print(tf.__version__)

1.13.1
